import image from "./js/image";
import { ResetSave } from "./js/ResetSave";
import { ImageEditing } from "./js/ImageEditing";
import { ButtonEditing } from "./js/ButtonEditing";
image();
const imgSrc = document.querySelector(".view-image img") as HTMLImageElement;
const resetButton = document.querySelector(".reset") as HTMLButtonElement;
const saveButton = document.querySelector(".save") as HTMLButtonElement;
new ResetSave(imgSrc, saveButton, resetButton);
new ImageEditing();
new ButtonEditing();
